Improve error message when backend fails to send device info
If connection fails early, frontend do not get any device information,
but it prints misleading message "Invalid speed received". The actual
cause may include:
 - unplugged device
 - qubes-usb-proxy not installed in the backend
 - unsupported device
 - ...

QubesOS/qubes-issues#3272
QubesOS/qubes-issues#3026

diff --git a/src/usb-import b/src/usb-import
--- a/src/usb-import
+++ b/src/usb-import
@@ -66,6 +66,12 @@ wait_for_attached() {
 # negotiate parameters (field 'extra' reserved for future use)
 read untrusted_devid untrusted_speed untrusted_extra
 
+# check for unexpected EOF
+if [ -z "$untrusted_devid" -a -z "$untrusted_speed" ]; then
+    echo "No device info received, connection failed, check backend side for details" >&2
+    exit 1
+fi
+
 case "$untrusted_speed" in
     1.5) speed=1 ;; # Low Speed
     12)  speed=2 ;; # Full speed
